//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scire.JTV.SynchronizeDB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("madq90swhEuaFABZvQcxO/RiMG2Te4dykrvcwLEXzvU0CL9ZT4TL0qgylBpi1ln3D6/+nWsHjSmn62WQq" +
            "IgajgvA34J3fYsU16HQ6hIFChezF2iDAUeahyFoy84KO6xtdDbIe5Pbjcbeg+7+bvLBEwTnVq7w8jCi8" +
            "YK4SfBxB0U=")]
        public string ConnectionTarget {
            get {
                return ((string)(this["ConnectionTarget"]));
            }
            set {
                this["ConnectionTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gwJJHXTwULp5CwVl/MoCuuK6bwPK0P2Prt0Or0RhKUVIEZpWYksnprrpXifrY77oFfPr1KkpAtiU+7V04" +
            "oG6Vg2TsWBrqhRz7Xh/UPShl4C5At1Lc4fpRJJcelH64iyZ9Q73j5BMF/cxpvHRRV3NXw==")]
        public string ConnectionSource {
            get {
                return ((string)(this["ConnectionSource"]));
            }
            set {
                this["ConnectionSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CodigoCliente {
            get {
                return ((int)(this["CodigoCliente"]));
            }
            set {
                this["CodigoCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TempoMinutos {
            get {
                return ((int)(this["TempoMinutos"]));
            }
            set {
                this["TempoMinutos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:59")]
        public string ResetBD {
            get {
                return ((string)(this["ResetBD"]));
            }
            set {
                this["ResetBD"] = value;
            }
        }
    }
}
